title: Ryan Ellison
logo: /docs/assets/img/Picture_Me.jpg

twitter: https://twitter.com/_Ryan_Ellison
linkedin: https://www.linkedin.com/in/ryan-ellison-b5b7b4159/
#github: https://github.com/vladUng
description: Ryan Ellison's Website
show_downloads: true
google_analytics: G-X7P50197W6
theme: just-the-docs

uni_taikai_york: /docs/assets/img/_Kendo_York_Edinburgh.jpeg
me_microscope: /docs/assets/img/Me_microscope.jpg
laidlaw_me_poster: /docs/assets/img/Laidlaw_Profile.jpg

gems:
  - jemoji